"""Generate host MCP client configs — default all planes, --enable/--disable."""

from __future__ import annotations

import os
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Literal

from .planes import list_plane_infos

Host = Literal["grok", "claude"]


@dataclass(frozen=True, slots=True)
class PlaneToggle:
    """Which planes are enabled for a client config."""

    enabled: tuple[str, ...]
    disabled: tuple[str, ...]
    all_planes: tuple[str, ...]

    def to_dict(self) -> dict[str, Any]:
        return {
            "enabled": list(self.enabled),
            "disabled": list(self.disabled),
            "all_planes": list(self.all_planes),
        }


def default_plane_ids() -> tuple[str, ...]:
    """Planes with installed deps (catalog, molcrafts, then α).

    Optional science packages that are not installed are omitted silently —
    no pytest-style skip; they simply never appear in client configs.
    """
    infos = list_plane_infos(include_unavailable_providers=False)
    ids = [p.id for p in infos]
    # Prefer catalog → molcrafts first, then the rest sorted.
    head = [x for x in ("catalog", "molcrafts") if x in ids]
    tail = sorted(x for x in ids if x not in head)
    return tuple(head + tail)


def resolve_plane_toggles(
    *,
    enable: list[str] | tuple[str, ...] = (),
    disable: list[str] | tuple[str, ...] = (),
    available: tuple[str, ...] | None = None,
) -> PlaneToggle:
    """Default: all planes on. Apply ``--disable`` then ``--enable``.

    Raises:
        ValueError: unknown plane id in enable/disable.
    """
    all_planes = available if available is not None else default_plane_ids()
    known = set(all_planes)
    enabled = set(all_planes)

    def _norm(name: str) -> str:
        return name.strip().lower()

    for raw in disable:
        plane = _norm(raw)
        if plane not in known:
            raise ValueError(f"unknown plane {plane!r}; known: {', '.join(all_planes)}")
        enabled.discard(plane)

    for raw in enable:
        plane = _norm(raw)
        if plane not in known:
            raise ValueError(f"unknown plane {plane!r}; known: {', '.join(all_planes)}")
        enabled.add(plane)

    if not enabled:
        raise ValueError("at least one plane must remain enabled")

    ordered = tuple(p for p in all_planes if p in enabled)
    disabled = tuple(p for p in all_planes if p not in enabled)
    return PlaneToggle(enabled=ordered, disabled=disabled, all_planes=all_planes)


def _molmcp_command() -> list[str]:
    """The command a *client* can launch, as an absolute path.

    Emitting the bare name assumed the client would resolve it on PATH.
    Desktop MCP hosts are started by the desktop session, whose PATH is the
    system default, so a virtualenv's bin directory is not on it — the
    config worked in the terminal that generated it and nowhere else.

    The fallback runs this very interpreter rather than ``python``, which on
    macOS frequently does not exist at all.

    Symlinks are deliberately left alone: ``molmcp`` is often a shim, and
    resolving through it would pin a path the installer may replace.
    """
    resolved = shutil.which("molmcp")
    if resolved:
        return [os.path.abspath(resolved)]
    return [sys.executable, "-m", "molmcp"]


def _toml_string(value: str) -> str:
    """Quote a TOML basic string.

    A Windows path is full of backslashes, and every one of them is an
    escape inside a basic string: hand-quoting produced a file no TOML
    parser would read back.
    """
    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )
    return f'"{escaped}"'


def serve_argv(plane: str) -> list[str]:
    return [*_molmcp_command(), "serve", plane]


def render_grok_toml(toggle: PlaneToggle) -> str:
    """Grok ``config.toml`` fragments for ``[mcp_servers.<plane>]``."""
    lines = [
        "# MolCrafts multi-plane MCP — generated by `molmcp client grok`",
        "# Default: all planes enabled. Re-run with --disable / --enable to change.",
        "",
    ]
    cmd = _molmcp_command()
    for plane in toggle.all_planes:
        on = plane in toggle.enabled
        lines.append(f"[mcp_servers.{plane}]")
        lines.append(f"command = {_toml_string(cmd[0])}")
        # args: rest of command + serve plane
        args = cmd[1:] + ["serve", plane]
        args_lit = ", ".join(_toml_string(a) for a in args)
        lines.append(f"args = [{args_lit}]")
        lines.append(f"enabled = {'true' if on else 'false'}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_claude_json(toggle: PlaneToggle) -> dict[str, Any]:
    """Claude Desktop / Code style ``mcpServers`` map (only enabled planes)."""
    cmd = _molmcp_command()
    servers: dict[str, Any] = {}
    for plane in toggle.enabled:
        servers[plane] = {
            "command": cmd[0],
            "args": cmd[1:] + ["serve", plane],
        }
    return {"mcpServers": servers}


def render_client(
    host: Host,
    *,
    enable: list[str] | tuple[str, ...] = (),
    disable: list[str] | tuple[str, ...] = (),
) -> tuple[PlaneToggle, str]:
    """Return (toggle, config text) for *host*."""
    toggle = resolve_plane_toggles(enable=enable, disable=disable)
    if host == "grok":
        return toggle, render_grok_toml(toggle)
    if host == "claude":
        import json

        return toggle, json.dumps(render_claude_json(toggle), indent=2) + "\n"
    raise ValueError(f"unknown host {host!r}")


def default_write_path(host: Host) -> Path:
    home = Path.home()
    if host == "grok":
        return home / ".grok" / "config.toml"
    # Claude Code often uses ~/.claude.json or project .mcp.json — emit fragment only.
    return home / ".claude" / "molmcp-mcp.json"


__all__ = [
    "Host",
    "PlaneToggle",
    "default_plane_ids",
    "default_write_path",
    "render_claude_json",
    "render_client",
    "render_grok_toml",
    "resolve_plane_toggles",
    "serve_argv",
]
