"""Read-only OKF curation planner for a candidate molexp workspace.

:func:`check_layout` is the entry point behind the ``molexp_check_layout``
tool. For an arbitrary directory it lints conformance (via
:func:`.layout.validate_workspace`) and proposes an **OKF curation plan** the
``mol:adopt-workspace`` skill / molexp's Python API can execute. The plan is a
*suggestion* to seed an operator-reviewed migration — this module never writes
a byte (per molmcp's provider-design contract, writes belong upstream).

The plan covers the three things the operator asked the command to (re)build,
all expressed against molexp's current OKF conventions:

* **scaffold** — the Workspace→Project→Experiment→Run mapping (each node tagged
  with its concept ``type``), the ``meta.yaml`` + ``index.md`` markers to write,
  the markdown-link knowledge graph, and the derived indexes molexp rebuilds
  (children ``*.json``, ``catalog/index.sqlite``, the Bundle ``index.json`` /
  ``INDEX.md``);
* **ingest** — existing files discovered in the tree (READMEs / ``*.md`` /
  ``*.bib`` / Zotero / PDFs) proposed as ``Note`` / ``ReferenceConcept`` OKF
  Concepts (PDFs pointed-at, never copied); and
* **llm_summaries** — a per-scope descriptive ``Note`` to be generated by an LLM.

Every walk is depth-bounded; exceeding a bound sets ``truncated`` (never a
silent cap).
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from . import layout

# Bounds, so a tool response can never grow unbounded (the response-limit
# middleware would otherwise truncate it opaquely). Exceeding any bound sets
# ``truncated`` — never a silent cap.
MAX_PROJECTS = 100
MAX_EXPERIMENTS = 100
MAX_RUNS = 200
MAX_INGEST = 200
MAX_SUMMARIES = 100

_DOC_EXTS = {".md", ".markdown"}
_TEXT_EXTS = {".txt", ".rst"}

# Per-ingest-kind hint for the executing skill: what OKF Concept to build.
_INGEST_NOTE = {
    "markdown": "import as a Note (note.note): meta.yaml + index.md body",
    "text": "import as a Note (note.note): meta.yaml + index.md body",
    "bibtex": "parse the .bib; add one ReferenceConcept (reference.reference) "
    "per entry, PDFs pointed-at via meta.yaml pdf_path",
    "zotero": "Bundle.import_zotero: link each item as a ReferenceConcept; "
    "PDFs pointed-at, never copied",
    "pdf": "attach as a ReferenceConcept pointed at this PDF via meta.yaml "
    "pdf_path (never copied)",
}


@dataclass(slots=True)
class _Scope:
    """A concept directory + the scope it maps to (for knowledge attribution)."""

    dir: Path
    kind: str  # workspace | project | experiment | run
    target_id: str


def _slugify(text: str) -> str:
    """Kebab-case approximation of molexp's slugify (executor applies the real one)."""
    slug = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return slug or "item"


def _classify(fname: str) -> tuple[str, str] | None:
    """Return ``(concept_type, kind)`` for an ingestable file, else ``None``."""
    lower = fname.lower()
    ext = Path(lower).suffix
    if lower == "zotero.sqlite":
        return ("reference.reference", "zotero")
    if ext == ".bib":
        return ("reference.reference", "bibtex")
    if ext == ".pdf":
        return ("reference.reference", "pdf")
    if ext in _DOC_EXTS or lower.startswith("readme"):
        return ("note.note", "markdown")
    if ext in _TEXT_EXTS:
        return ("note.note", "text")
    return None


def _run_dir_name(name: str) -> str:
    return name if name.startswith("run-") else f"run-{name}"


def _walk_build(root: Path) -> tuple[dict[str, Any], list[_Scope], bool]:
    """Heuristic tree + flat scope list for a directory that is NOT a workspace.

    Depth-based and intentionally simple: top-level dirs become projects, their
    subdirs experiments, the next level runs. A suggestion, never an assertion.
    """
    truncated = False
    workspace_id = _slugify(root.name)
    scopes = [_Scope(root, "workspace", workspace_id)]
    projects: list[dict[str, Any]] = []
    for proj in layout.child_dirs(root):
        if len(projects) >= MAX_PROJECTS:
            truncated = True
            break
        scopes.append(_Scope(proj, "project", proj.name))
        experiments: list[dict[str, Any]] = []
        for exp in layout.child_dirs(proj):
            if len(experiments) >= MAX_EXPERIMENTS:
                truncated = True
                break
            scopes.append(_Scope(exp, "experiment", exp.name))
            runs: list[dict[str, str]] = []
            for run in layout.child_dirs(exp):
                if len(runs) >= MAX_RUNS:
                    truncated = True
                    break
                scopes.append(_Scope(run, "run", _run_dir_name(run.name)))
                runs.append(
                    {
                        "source_dir": run.name,
                        "target_dir": _run_dir_name(run.name),
                        "concept_type": "workspace.run",
                    }
                )
            experiments.append(
                {
                    "name": exp.name,
                    "target_id": exp.name,
                    "source_dir": exp.name,
                    "concept_type": "workspace.experiment",
                    "runs": runs,
                }
            )
        projects.append(
            {
                "name": proj.name,
                "target_id": proj.name,
                "source_dir": proj.name,
                "concept_type": "workspace.project",
                "experiments": experiments,
            }
        )
    mapping = {
        "workspace_id": workspace_id,
        "concept_type": "workspace.root",
        "projects": projects,
    }
    return mapping, scopes, truncated


def _walk_repair(root: Path) -> tuple[list[_Scope], bool]:
    """Flat scope list for an EXISTING workspace (walks the conformant tree)."""
    truncated = False
    scopes = [_Scope(root, "workspace", _slugify(root.name))]
    n_proj = 0
    for proj in layout.child_dirs(root / "projects"):
        if n_proj >= MAX_PROJECTS:
            truncated = True
            break
        n_proj += 1
        scopes.append(_Scope(proj, "project", proj.name))
        for exp in layout.child_dirs(proj / "experiments"):
            scopes.append(_Scope(exp, "experiment", exp.name))
            for run in layout.child_dirs(exp / "runs"):
                scopes.append(_Scope(run, "run", run.name))
    return scopes, truncated


def _scan_knowledge(
    root: Path, scopes: list[_Scope]
) -> tuple[list[dict[str, Any]], bool]:
    """Discover ingestable files in each scope dir (top-level files only)."""
    ingest: list[dict[str, Any]] = []
    truncated = False
    for sc in scopes:
        for f in sorted(sc.dir.iterdir()):
            if not f.is_file() or f.is_symlink() or f.name.startswith("."):
                continue
            classified = _classify(f.name)
            if classified is None:
                continue
            if len(ingest) >= MAX_INGEST:
                truncated = True
                break
            concept_type, kind = classified
            ingest.append(
                {
                    "source_file": f.relative_to(root).as_posix(),
                    "scope_kind": sc.kind,
                    "scope_id": sc.target_id,
                    "proposed_concept_type": concept_type,
                    "proposed_name": _slugify(f.stem),
                    "kind": kind,
                    "note": _INGEST_NOTE[kind],
                }
            )
        if truncated:
            break
    return ingest, truncated


def _propose_summaries(scopes: list[_Scope]) -> tuple[list[dict[str, Any]], bool]:
    """One LLM-summary Note per workspace/project/experiment scope (skip runs)."""
    out: list[dict[str, Any]] = []
    truncated = False
    for sc in scopes:
        if sc.kind == "run":
            continue
        if len(out) >= MAX_SUMMARIES:
            truncated = True
            break
        out.append(
            {
                "scope_kind": sc.kind,
                "scope_id": sc.target_id,
                "proposed_note_name": "summary",
                "prompt_hint": f"Summarize the {sc.kind} '{sc.target_id}' from "
                "its contents / params / artifacts as an OKF Note (note.note).",
            }
        )
    return out, truncated


def _missing_markers(scopes: list[_Scope]) -> tuple[list[dict[str, str]], bool]:
    """Concept dirs in an existing workspace lacking the mandatory meta.yaml."""
    out: list[dict[str, str]] = []
    truncated = False
    for sc in scopes:
        if (sc.dir / layout.META_YAML).is_file():
            continue
        if len(out) >= MAX_INGEST:
            truncated = True
            break
        out.append(
            {
                "path": str(sc.dir),
                "marker": layout.META_YAML,
                "scope_kind": sc.kind,
                "scope_id": sc.target_id,
            }
        )
    return out, truncated


def _scaffold(missing_markers: list[dict[str, str]]) -> dict[str, Any]:
    """The OKF markers + derived-index rebuilds the executor must perform."""
    return {
        "concept_markers": "For every concept dir write meta.yaml (its "
        "registered type + id) and an index.md narrative.",
        "knowledge_graph": "Link workspace→project→experiment→run (and each "
        "note→the references it cites) via markdown links in index.md; those "
        "links are the OKF out-edges.",
        "missing_markers": missing_markers,
        "rebuild_derived": [dict(f) for f in layout.DERIVED_FILES],
    }


def _knowledge(root: Path, scopes: list[_Scope]) -> tuple[dict[str, Any], bool]:
    ingest, t1 = _scan_knowledge(root, scopes)
    summaries, t2 = _propose_summaries(scopes)
    return {"ingest": ingest, "llm_summaries": summaries}, (t1 or t2)


def _early(root: Path, *, exists: bool, rule: str, detail: str) -> dict[str, Any]:
    """Uniform shape for the not-exists / not-a-directory short circuits."""
    return {
        "path": str(root),
        "exists": exists,
        "is_workspace": False,
        "conforms": False,
        "violations": [{"path": str(root), "rule": rule, "detail": detail}],
        "proposed_curation": None,
        "truncated": False,
        "summary": detail.capitalize() + ".",
    }


def check_layout(path: str | Path) -> dict[str, Any]:
    """Read-only conformance check + OKF curation plan for ``path``.

    Returns a single dict: whether ``path`` is already a molexp workspace,
    whether it conforms to the naming + OKF laws, the concrete violations, and
    a ``proposed_curation`` plan (``kind='build'`` for a non-workspace tree,
    ``kind='repair'`` for an existing workspace with gaps or ingestable
    knowledge, ``None`` for a clean conformant workspace). No writes occur.
    """
    root = Path(path)
    if not root.exists():
        return _early(root, exists=False, rule="exists", detail="path does not exist")
    if not root.is_dir():
        return _early(
            root, exists=True, rule="is_dir", detail="path is not a directory"
        )

    found = layout.Findings()
    is_workspace = (root / "workspace.json").is_file()

    if is_workspace:
        layout.validate_workspace(root, found)
        scopes, t_walk = _walk_repair(root)
        missing, t_mark = _missing_markers(scopes)
        knowledge, t_know = _knowledge(root, scopes)
        conforms = not found.violations
        needs_curation = bool(missing or knowledge["ingest"])
        proposed = (
            {
                "kind": "repair",
                "workspace_id": _slugify(root.name),
                "mapping": None,
                "scaffold": _scaffold(missing),
                "knowledge": knowledge,
            }
            if needs_curation
            else None
        )
        truncated = found.truncated or t_walk or t_mark or t_know
        summary = _repair_summary(conforms, found.violations, missing, knowledge)
        return _result(root, True, conforms, found, proposed, truncated, summary)

    found.add(
        root,
        "missing_workspace_json",
        "no workspace.json — not a molexp workspace; see proposed_curation",
    )
    mapping, scopes, t_walk = _walk_build(root)
    knowledge, t_know = _knowledge(root, scopes)
    proposed = {
        "kind": "build",
        "workspace_id": mapping["workspace_id"],
        "mapping": mapping,
        "scaffold": _scaffold([]),
        "knowledge": knowledge,
    }
    truncated = found.truncated or t_walk or t_know
    n_proj = len(mapping["projects"])
    n_ingest = len(knowledge["ingest"])
    summary = (
        f"Not a molexp workspace. Proposed {n_proj} project(s) and "
        f"{n_ingest} knowledge item(s) to ingest; hand proposed_curation to "
        "mol:adopt-workspace to materialize."
    )
    return _result(root, False, False, found, proposed, truncated, summary)


def _repair_summary(
    conforms: bool,
    violations: list[dict[str, str]],
    missing: list[dict[str, str]],
    knowledge: dict[str, Any],
) -> str:
    if conforms and not missing and not knowledge["ingest"]:
        return "Conforms to the molexp OKF layout spec."
    parts: list[str] = []
    if violations:
        parts.append(f"{len(violations)} layout violation(s)")
    if knowledge["ingest"]:
        parts.append(f"{len(knowledge['ingest'])} knowledge item(s) to ingest")
    detail = "; ".join(parts) if parts else "scaffold gaps"
    return f"molexp workspace with {detail}; see proposed_curation."


def _result(
    root: Path,
    is_workspace: bool,
    conforms: bool,
    found: layout.Findings,
    proposed: dict[str, Any] | None,
    truncated: bool,
    summary: str,
) -> dict[str, Any]:
    return {
        "path": str(root),
        "exists": True,
        "is_workspace": is_workspace,
        "conforms": conforms,
        "violations": found.violations,
        "proposed_curation": proposed,
        "truncated": truncated,
        "summary": summary,
    }
